os: linux
dist: focal
language: python
python: 3.8
cache: pip
before_install: pip install --upgrade pip setuptools six
install: pip install -r requirements.txt
before_script:
  - black --check . || true
script:
  - mypy --ignore-missing-imports .
  - pytest --doctest-modules
  - coverage run -m unittest discover
after_success:
  - python scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
